# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e403c6ee916a9e4f7c3e5773257b3413dd796ecd16f657edfe7d43efbddc7248811fe877d0a453856cda46d153005c3be04bb6ce467851f5083729afbadcdc0a

test:
  secret_key_base: 810992322127a8734b8c7eea5e7f0f47f8bffc98816503591a9cdd8d9287678039ee1982ef02018d58e16adf30334af9a9df9730c16119cc8e673c437926a819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
